spring:
  cloud:
    gateway:
      discovery:
        locator:
#         是否与服务发现组件进行结合,通过 serviceId 转发到具体的服务实例
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: after_route
          uri: https://example.org
          predicates:
            - Cookie=mycookie,mycookievalue
